export default [
 {
   "firstName": "Dimitri",
   "lastName": "Apassov",
   "email": "dmitri.apassov@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marina",
   "lastName": "Maiorana",
   "email": "marina_maiorana@hotmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Helena",
   "lastName": "Thorarins",
   "email": "helena.thorarins@claremont.se",
   "phone": " 460708786858",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Christina",
   "lastName": "Ntis",
   "email": "ntis@kth.se",
   "phone": " 460704425704",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Dmitri",
   "lastName": "Apassov",
   "email": "d_apassov@yahoo.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Segen",
   "lastName": "Menghes",
   "email": "segen.menghes@gmail.com",
   "phone": " 46760853658",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Samuel",
   "lastName": "Spik",
   "email": "samuel.spik@outlook.com",
   "phone": " 46769356828",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Nilsson",
   "email": "marcus.nilsson@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Towe",
   "lastName": "Warland",
   "email": "towe.varland@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tharanga",
   "lastName": "kulamithra",
   "email": "tharanga.kulamithra@claremont.se",
   "phone": " 46705875080",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Wassberg",
   "email": "fredrik.wassberg@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Susanna",
   "lastName": "Björklund",
   "email": "susanna.bjorklund@claremont.se",
   "phone": " 46735444732",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Cristine",
   "lastName": "Norlander",
   "email": "cristine.norlander@claremont.se",
   "phone": " 460760541409",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "mathias",
   "lastName": "wadsten",
   "email": "mathiaswadsten@hotmail.com",
   "phone": " 46703440256",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Martin",
   "lastName": "Christensen",
   "email": "martin@agileux.se",
   "phone": " 46733283553",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anders",
   "lastName": "Eng",
   "email": "anders.eng@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Eric",
   "lastName": "Schumertl",
   "email": "eric.schumertl@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mikael",
   "lastName": "Jonsson",
   "email": "mikael.jonsson@claremont.se",
   "phone": " 460708865423",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Olof",
   "lastName": "Soldatic",
   "email": "olof.soldatic@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Didrik",
   "lastName": "Helsing",
   "email": "didrik.helsing@claremont.se",
   "phone": " 46705557780",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linn",
   "lastName": "Ängré",
   "email": "linn.angre@claremont.se",
   "phone": " 46707200226",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Axel",
   "lastName": "Dahlberg",
   "email": "axeldahlberg@gmail.com",
   "phone": " 46730516768",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Engin",
   "lastName": "Marshall",
   "email": "engin.marshall@claremont.se",
   "phone": " 460720028800",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ingela",
   "lastName": "Hagman",
   "email": "ingela.hagman@claremont.se",
   "phone": " 46721504075",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustaf",
   "lastName": "Hillver",
   "email": "gustaf.hillver@gmail.com",
   "phone": " 460708587676",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Eddie",
   "lastName": "Andersson",
   "email": "eddie.andersson@live.se",
   "phone": " 4672 245 33 33",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Daniel",
   "lastName": "Litsesjö",
   "email": "daniel.litsesjo@claremont.se",
   "phone": " 46707199154",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Eyasu",
   "lastName": "Alemayehu",
   "email": "eyasu.alemayehu@claremont.se",
   "phone": " 460760540474",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Felicia",
   "lastName": "Falck",
   "email": "felicia.falck@claremont.se",
   "phone": " 46704283893",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustav",
   "lastName": "Fridh",
   "email": "gustav.fridh@claremont.se",
   "phone": " 46736605411",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Nilborn",
   "email": "jonas.nilborn@claremont.se",
   "phone": " 460722365820",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Kristoffer",
   "lastName": "Hemlin",
   "email": "kristoffer.hemlin@claremont.se",
   "phone": " 46706349637",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Frisell",
   "email": "marcus.frisell@claremont.se",
   "phone": " 46738064585",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sebastian",
   "lastName": "Bäckström Pino",
   "email": "sebastian.pino-backstrom@claremont.se",
   "phone": " 46768847076",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Simon",
   "lastName": "Ekizean",
   "email": "simon.ekizean@claremont.se",
   "phone": " 46735748330",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "William",
   "lastName": "Larsten",
   "email": "william.larsten@claremont.se",
   "phone": " 46736240010",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alexandra",
   "lastName": "Dabo",
   "email": "alexandra.dabo@claremont.se",
   "phone": " 460761371390",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alexandra",
   "lastName": "Nordeborg",
   "email": "alexandra.nordeborg@claremont.se",
   "phone": " 46760-614840",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anders",
   "lastName": "Sderman",
   "email": "anders.soderman@claremont.se",
   "phone": " 46700039660",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andre",
   "lastName": "Witte",
   "email": "andree.witte@claremont.se",
   "phone": " 460735252636",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Salomon-Sorensen",
   "email": "anna.salomon-sorensen@claremont.se",
   "phone": " 46709906097",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Clara",
   "lastName": "Berg",
   "email": "clara.berg@claremont.se",
   "phone": " 46761645414",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Erika",
   "lastName": "Hernandez",
   "email": "erika.hernandez@claremont.se",
   "phone": " 460736711456",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Frida",
   "lastName": "Emesten-Rahm",
   "email": "frida.emesten-rahm@claremont.se",
   "phone": " 46736342551",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Galina",
   "lastName": "Psibilskiene",
   "email": "galina.psibilskiene@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jakob",
   "lastName": "Söderbaum",
   "email": "jakob.soderbaum@claremont.se",
   "phone": " 46707449784",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Josefine",
   "lastName": "Lundgren",
   "email": "josefine.lundgren@claremont.se",
   "phone": " 46738484460",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Lena",
   "lastName": "Brelin",
   "email": "lena.brelin@claremont.se",
   "phone": " 46768593882",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linda",
   "lastName": "Haag Westvall",
   "email": "linda.haag.westvall@claremont.se",
   "phone": " 460704217434",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linus",
   "lastName": "Gustafsson",
   "email": "linus.gustafsson@claremont.se",
   "phone": " 460767866547",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Ekelund",
   "email": "marcus.ekelund@claremont.se",
   "phone": " 460720802962",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Natalie",
   "lastName": "Alenheim",
   "email": "natalie.alenheim@claremont.se",
   "phone": " 46734449198",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Natalie",
   "lastName": "Ebenfelt",
   "email": "natalie.ebenfelt@claremont.se",
   "phone": " 460706391888",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Nici",
   "lastName": "Grufman",
   "email": "nici.grufman@claremont.se",
   "phone": " 460733870702",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Per",
   "lastName": "Thörnqvist",
   "email": "per.thornqvist@claremont.se",
   "phone": " 46707704045",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Philip",
   "lastName": "Groppfeldt",
   "email": "philip.groppfeldt@claremont.se",
   "phone": " 46706444121",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Robin",
   "lastName": "Fredriksson",
   "email": "robin.fredriksson@claremont.se",
   "phone": " 460702584391",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sophie",
   "lastName": "garcia",
   "email": "sophie.garcia@claremont.se",
   "phone": " 46733260702",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Suzan",
   "lastName": "Pastuhovic",
   "email": "suzan.pastuhovic@claremont.se",
   "phone": " 46738902985",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alexander",
   "lastName": "Hemberg",
   "email": "alexander.hemberg@claremont.se",
   "phone": " 46704940405",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Elof",
   "lastName": "Bigestans",
   "email": "elof.bigestans@claremont.se",
   "phone": " 46762211288",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linda",
   "lastName": "Andersson",
   "email": "linda.andersson@claremont.se",
   "phone": " 460736783320",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tony",
   "lastName": "Brunstedt",
   "email": "tony.brunstedt@claremont.se",
   "phone": " 46736552921",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alfred",
   "lastName": "Guirguis",
   "email": "alfred.guirguis@claremont.se",
   "phone": " 460725475024",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Annelie",
   "lastName": "Ribba Bergman",
   "email": "annelie.bergman@claremont.se",
   "phone": " 46733173409",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anton",
   "lastName": "Uppstrm",
   "email": "anton.uppstrom@claremont.se",
   "phone": " 460768117092",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Bjarki",
   "lastName": "Helgason",
   "email": "bjarki.helgason@claremont.se",
   "phone": " 460709266963",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carolina",
   "lastName": "Stlhammar",
   "email": "carolina.stalhammar@claremont.se",
   "phone": " 460701447172",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Cecilia",
   "lastName": "Welander",
   "email": "cecilia.welander@claremont.se",
   "phone": " 46707498026",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Christian",
   "lastName": "Sternudd",
   "email": "christian.sternudd@claremont.se",
   "phone": " 46706050936",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Eric",
   "lastName": "Kalmelid",
   "email": "eric.kalmelid@claremont.se",
   "phone": " 46702232950",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Eva",
   "lastName": "Sandgren",
   "email": "eva.sandgren@claremont.se",
   "phone": " 4646708185910",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Henrik",
   "lastName": "Brinkhagen",
   "email": "henrik.brinkhagen@claremont.se",
   "phone": " 460727165555",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Ploski",
   "email": "johan.ploski@claremont.se",
   "phone": " 46070 275 91 91",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Sedin",
   "email": "jonas.sedin@claremont.se",
   "phone": " 46730746812",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Tillhagen",
   "email": "jonas.tillhagen@claremont.se",
   "phone": " 460725432434",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Kristian",
   "lastName": "Karre",
   "email": "kristian.karre@claremont.se",
   "phone": " 460707881020",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Malin",
   "lastName": "Misaghi",
   "email": "malin.misaghi@claremont.se",
   "phone": " 46733641881",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Aladin",
   "lastName": "Galjic",
   "email": "aladin.galjic@claremont.se",
   "phone": " 46737088089",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carl",
   "lastName": "Hellström",
   "email": "carl.hellstrom@claremont.se",
   "phone": " 46739977676",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Christian",
   "lastName": "Planebrink",
   "email": "christian.planebrink@claremont.se",
   "phone": " 460708797041",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Davide",
   "lastName": "Bellman",
   "email": "davide.bellman@claremont.se",
   "phone": " 46737825393",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Lavesson",
   "email": "fredrik.lavesson@claremont.se",
   "phone": " 46703535859",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Furkan",
   "lastName": "Poyraz",
   "email": "furkan.poyraz@claremont.se",
   "phone": " 46763114875",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jan",
   "lastName": "Pettersson",
   "email": "jan.pettersson@claremont.se",
   "phone": " 46706291395",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Grahn",
   "email": "johan.grahn@claremont.se",
   "phone": " 4646727309392",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Lukas",
   "lastName": "Lindn",
   "email": "lukas.linden@claremont.se",
   "phone": " 460722208068",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Maria",
   "lastName": "hsberg",
   "email": "maria.ahsberg@claremont.se",
   "phone": " 460704228559",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marouf",
   "lastName": "Hussain",
   "email": "marouf.hussain@claremont.se",
   "phone": " 460720326815",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Miriam",
   "lastName": "Wennbom",
   "email": "miriam.wennbom@claremont.se",
   "phone": " 46730301311",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sabine",
   "lastName": "Möller",
   "email": "sabine.moller@claremont.se",
   "phone": " 460722325777",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Susanne",
   "lastName": "Malmhake",
   "email": "susanne.malmhake@claremont.se",
   "phone": " 460703779070",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Thomas",
   "lastName": "Lindahl",
   "email": "thomas.lindahl@claremont.se",
   "phone": " 46709517700",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carolina",
   "lastName": "Edgren",
   "email": "carolina.edgren@claremont.se",
   "phone": " 460730294726",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Dini",
   "lastName": "Rahmawati",
   "email": "dini.rahmawati@claremont.se",
   "phone": " 46764097647",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Emma",
   "lastName": "Olander",
   "email": "emma.olander@claremont.se",
   "phone": " 46703435455",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Erik",
   "lastName": "Björling",
   "email": "erik.bjorling@claremont.se",
   "phone": " 46705204555",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Erik",
   "lastName": "Bohm",
   "email": "erik.bohm@claremont.se",
   "phone": " 46735700733",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredric",
   "lastName": "Larsson",
   "email": "fredric.larsson@claremont.se",
   "phone": " 46703666886",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gunnar",
   "lastName": "Möschler",
   "email": "gunnar.moschler@claremont.se",
   "phone": " 46722059409",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Hans",
   "lastName": "Leijström",
   "email": "hans.leijstrom@claremont.se",
   "phone": " 46705875701",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jan",
   "lastName": "Heggen",
   "email": "jan.heggen@claremont.se",
   "phone": " 4646707974101",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jon",
   "lastName": "Bergqvist",
   "email": "jon.bergqvist@claremont.se",
   "phone": " 460709307240",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Kajsa",
   "lastName": "Grens",
   "email": "kajsa.grenas@claremont.se",
   "phone": " 46703226924",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Karin",
   "lastName": "Ohlsson",
   "email": "karin.ohlsson@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Leonard",
   "lastName": "Bachner",
   "email": "leonard.bachner@claremont.se",
   "phone": " 460707181824",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Martin",
   "lastName": "Wallenius",
   "email": "martin.wallenius@claremont.se",
   "phone": " 460705703234",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Michael",
   "lastName": "Granath",
   "email": "michael.granath@claremont.se",
   "phone": " 460730746690",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Soheil",
   "lastName": "Baranji",
   "email": "soheil.baranji@claremont.se",
   "phone": " 46700 927 966",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alexander",
   "lastName": "Arozin",
   "email": "alexander.arozin@claremont.se",
   "phone": " 466473476",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andreas",
   "lastName": "Clauss",
   "email": "andreas.clauss@claremont.se",
   "phone": " 460707707840",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andriy",
   "lastName": "Lfberg",
   "email": "andriy.lofberg@claremont.se",
   "phone": " 46703696040",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Svahn",
   "email": "anna.svahn@claremont.se",
   "phone": " 460706065881",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Daniela",
   "lastName": "Hjälmbrink",
   "email": "daniela.hjalmbrink@claremont.se",
   "phone": " 46768189990",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "David",
   "lastName": "Nilsson",
   "email": "david.nilsson@claremont.se",
   "phone": " 460703095317",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Evert",
   "lastName": "Lagerberg",
   "email": "evert.lagerberg@claremont.se",
   "phone": " 46701619960",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Widén",
   "email": "fredrik.widen@claremont.se",
   "phone": " 46739863029",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustav",
   "lastName": "Näsman",
   "email": "gustav.nasman@claremont.se",
   "phone": " 46705878699",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Boström",
   "email": "johan.bostrom@claremont.se",
   "phone": " 460735454337",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Sjöberg",
   "email": "johan.sjoberg@claremont.se",
   "phone": " 46707210722",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonathan",
   "lastName": "Norén",
   "email": "jonathan.noren@claremont.se",
   "phone": " 460702148002",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Karin",
   "lastName": "Kåberg",
   "email": "karin.kaberg@claremont.se",
   "phone": " 46708441059",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Katharina",
   "lastName": "Ljunggren",
   "email": "katharina.ljunggren@claremont.se",
   "phone": " 46761047795",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Klara",
   "lastName": "Nieriker",
   "email": "klara.nieriker@claremont.se",
   "phone": " 460707708982",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Knut",
   "lastName": "Karlberg",
   "email": "knut.karlberg@claremont.se",
   "phone": " 4646761099784",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Kristoffer",
   "lastName": "Johansson",
   "email": "kristoffer.johansson@claremont.se",
   "phone": " 460707432131",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linda",
   "lastName": "Wohlfeil",
   "email": "linda.wohlfeil@claremont.se",
   "phone": " 460708669940",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Zalitis",
   "email": "marcus.zalitis@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mattias",
   "lastName": "Harneman",
   "email": "mattias.harneman@claremont.se",
   "phone": " 46709603344",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Melissa",
   "lastName": "Freiser",
   "email": "melissa.freiser@claremont.se",
   "phone": " 46763454840",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Michael",
   "lastName": "Desell",
   "email": "michael.desell@claremont.se",
   "phone": " 46734449211",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Michael",
   "lastName": "Nylund",
   "email": "michael.nylund@claremont.se",
   "phone": " 46701606406",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Niclas",
   "lastName": "Junsved",
   "email": "niclas.junsved@claremont.se",
   "phone": " 460732019077",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Oskar",
   "lastName": "Ingberg",
   "email": "oskar.ingberg@claremont.se",
   "phone": " 460760597835",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Patrik",
   "lastName": "Jansson",
   "email": "patrik.jansson@claremont.se",
   "phone": " 46736945098",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Patrik",
   "lastName": "Jellerbo",
   "email": "patrik.jellerbo@claremont.se",
   "phone": " 460736421052",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Pontus",
   "lastName": "Dreij",
   "email": "pontus.dreij@claremont.se",
   "phone": " 460702153662",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Robin",
   "lastName": "Weidelid",
   "email": "robin.weidelid@claremont.se",
   "phone": " 460766345566",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Staffan",
   "lastName": "Persson",
   "email": "staffan.persson1@claremont.se",
   "phone": " 46739459279",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Wick",
   "email": "anna.wick@claremont.se",
   "phone": " 46706040264",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Camilla",
   "lastName": "Lundblad",
   "email": "camilla.lundblad@claremont.se",
   "phone": " 46736871112",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Damir",
   "lastName": "Futic",
   "email": "damir.futic@claremont.se",
   "phone": " 46737093780",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Bergström",
   "email": "fredrik.bergstrom@claremont.se",
   "phone": " 460704990017",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Hedberg",
   "email": "johan.hedberg@claremont.se",
   "phone": " 460762218885",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Magdalena",
   "lastName": "Crona",
   "email": "magdalena.crona@claremont.se",
   "phone": " 46703269938",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Martin",
   "lastName": "Smolka",
   "email": "martin.smolka@claremont.se",
   "phone": " 46709689816",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mattias",
   "lastName": "Johansson",
   "email": "mattias.johansson@claremont.se",
   "phone": " 46707776209",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Olivia",
   "lastName": "Klees",
   "email": "olivia.klees@claremont.se",
   "phone": " 460708747005",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Alex",
   "lastName": "Karlsson",
   "email": "alex.karlsson@claremont.se",
   "phone": " 46739565735",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Axel",
   "lastName": "Lundström",
   "email": "axel.lundstrom@claremont.se",
   "phone": " 460762394639",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Emanuel",
   "lastName": "Angerbjrn",
   "email": "emanuel.angerbjorn@claremont.se",
   "phone": " 460735044124",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Blanco",
   "email": "fredrik.blanco@claremont.se",
   "phone": " 46703065555",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustaf",
   "lastName": "Eldh",
   "email": "gustaf.isaksson.eldh@claremont.se",
   "phone": " 46761341223",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustav",
   "lastName": "Angerbjörn",
   "email": "gustav.angerbjorn@claremont.se",
   "phone": " 460735044209",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ivan",
   "lastName": "Malmberg",
   "email": "ivan.malmberg@claremont.se",
   "phone": " 460762052736",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Aspemo",
   "email": "jonas.aspemo@claremont.se",
   "phone": " 46735169278",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mattias",
   "lastName": "Kedling",
   "email": "mattias.kedling@claremont.se",
   "phone": " 460739335198",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mikael",
   "lastName": "Milberger",
   "email": "mikael.milberger@claremont.se",
   "phone": " 46702434030",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Milica",
   "lastName": "Spasenovic",
   "email": "milica.spasenovic@claremont.se",
   "phone": " 460769029069",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Milos",
   "lastName": "Kalab",
   "email": "milos.kalab@claremont.se",
   "phone": " 460721648005",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Oliver",
   "lastName": "Hekmatara",
   "email": "oliver.hekmatara@claremont.se",
   "phone": " 460733583208",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ornamo",
   "lastName": "Antar",
   "email": "ornamo.antar@claremont.se",
   "phone": " 46733370292",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Pontus",
   "lastName": "Ellboj",
   "email": "pontus.ellboj@claremont.se",
   "phone": " 46736744616",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Viktor",
   "lastName": "Waagaard",
   "email": "viktor.waagaard@claremont.se",
   "phone": " 46720455828",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andreas",
   "lastName": "Åkerblad",
   "email": "andreas.akerblad@claremont.se",
   "phone": " 46702609977",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Henrik",
   "lastName": "Agaeus",
   "email": "henrik.agaeus@claremont.se",
   "phone": " 460706050758",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Nielsen",
   "email": "jonas.nielsen@claremont.se",
   "phone": " 460725615244",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Milad",
   "lastName": "Taba",
   "email": "milad.taba@claremont.se",
   "phone": " 460762214123",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ulf",
   "lastName": "Bonde Åkerlind",
   "email": "ulf.bonde-akerlind@claremont.se",
   "phone": " 46706665708",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Åke",
   "lastName": "Demander",
   "email": "ake.demander@claremont.se",
   "phone": " 46703306566",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carina",
   "lastName": "Hglund",
   "email": "carina.hoglund@claremont.se",
   "phone": " 460707174022",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Christoffer",
   "lastName": "Broström",
   "email": "christoffer.brostrom@claremont.se",
   "phone": " 46707753696",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Elin",
   "lastName": "Hellström",
   "email": "elin.hellstrom@claremont.se",
   "phone": " 46733607249",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Lengqvist",
   "email": "johan.lengqvist@claremont.se",
   "phone": " 460706024603",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Sjöblom",
   "email": "jonas.sjoblom@claremont.se",
   "phone": " 460702376417",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Michael",
   "lastName": "Ståhle",
   "email": "michael.stahle@claremont.se",
   "phone": " 46707217167",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Olga",
   "lastName": "Cheban",
   "email": "olga.cheban@claremont.se",
   "phone": " 460701457697",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Roger",
   "lastName": "Kalliomäki",
   "email": "roger.kalliomaki@claremont.se",
   "phone": " 46736810580",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Joakim",
   "lastName": "Englund",
   "email": "joakim.englund@claremont.se",
   "phone": " 46708334114",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Joakim",
   "lastName": "Svensson",
   "email": "joakim.svensson@claremont.se",
   "phone": " 46722082241",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johnny",
   "lastName": "Ho",
   "email": "johnny.ho@claremont.se",
   "phone": " 460723869842",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sofia",
   "lastName": "Sparr",
   "email": "sofia.sparr@claremont.se",
   "phone": " 46734449112",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andreas",
   "lastName": "Smidelöv",
   "email": "andreas.smidelov@claremont.se",
   "phone": " 46762007274",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Arvid",
   "lastName": "Sätterkvist",
   "email": "arvid.satterkvist@claremont.se",
   "phone": " 46730676764",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "David",
   "lastName": "Andersson",
   "email": "david.andersson@claremont.se",
   "phone": " 46760243118",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Erik",
   "lastName": "Forsberg",
   "email": "erik.forsberg@claremont.se",
   "phone": " 46730395145",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Filip",
   "lastName": "Wikström",
   "email": "filip.wikstrom@claremont.se",
   "phone": " 46761616693",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johannes",
   "lastName": "Smidelöv",
   "email": "johannes.smidelov@claremont.se",
   "phone": " 460707587371",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Oscar",
   "lastName": "Svensson",
   "email": "oscar.svensson@claremont.se",
   "phone": " 46072223613",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Björn",
   "lastName": "Carlander",
   "email": "bjorn.carlander@claremont.se",
   "phone": " 460730838737",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carin",
   "lastName": "Gustring",
   "email": "carin.gustring@claremont.se",
   "phone": " 460761750034",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fredrik",
   "lastName": "Tenbrink",
   "email": "fredrik.tenbrink@claremont.se",
   "phone": " 460733260060",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Hans",
   "lastName": "Svedåker",
   "email": "hans.svedaker@claremont.se",
   "phone": " 460725866898",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Hossein",
   "lastName": "Jeddi Tehrani",
   "email": "hossein.jeddi-tehrani@claremont.se",
   "phone": " 460735673156",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Joakim",
   "lastName": "Eriksson",
   "email": "joakim.eriksson@claremont.se",
   "phone": " 46730740282",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Strömhielm",
   "email": "johan.stromhielm@claremont.se",
   "phone": " 460733481658",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Feldt",
   "email": "jonas.feldt@claremont.se",
   "phone": " 46704440713",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Thuvesson Winberg",
   "email": "jonas.thuvesson-winberg@claremont.se",
   "phone": " 460737470702",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Olof",
   "lastName": "Wessel",
   "email": "olle.wessel@claremont.se",
   "phone": " 46730825438",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Per",
   "lastName": "Andersson",
   "email": "per.andersson@claremont.se",
   "phone": " 46706999230",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Philip",
   "lastName": "Brlin",
   "email": "philip.borlin@claremont.se",
   "phone": " 46733368007",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Rickard",
   "lastName": "Svensson",
   "email": "rickard.svensson@claremont.se",
   "phone": " 460707230435",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Robin",
   "lastName": "Jakobsson",
   "email": "robin.jakobsson@claremont.se",
   "phone": " 46765542714",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Agnes",
   "lastName": "Lind",
   "email": "agnes.lind@claremont.se",
   "phone": " 46763119836",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Beatrice",
   "lastName": "Lindberg",
   "email": "beatrice.lindberg@claremont.se",
   "phone": " 46709328300",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Caroline",
   "lastName": "Blomquist",
   "email": "caroline.blomquist@claremont.se",
   "phone": " 46734449152",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fabi",
   "lastName": "Khan",
   "email": "fabi.khan@claremont.se",
   "phone": " 46046700915490",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Felicia",
   "lastName": "Nieminen",
   "email": "felicia.nieminen@claremont.se",
   "phone": " 460701438989",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Jansson",
   "email": "johan.jansson@claremont.se",
   "phone": " 460703856377",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linda",
   "lastName": "Ohlsson",
   "email": "linda.ohlsson@claremont.se",
   "phone": " 460709424907",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Magnus",
   "lastName": "Thernelius",
   "email": "magnus.thernelius@claremont.se",
   "phone": " 46708282248",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Michael",
   "lastName": "Karlsson",
   "email": "michael.karlsson@claremont.se",
   "phone": " 46706962306",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "My",
   "lastName": "Westin",
   "email": "my.westin@claremont.se",
   "phone": " 460708589927",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Peter",
   "lastName": "Ahlberg",
   "email": "peter.ahlberg@claremont.se",
   "phone": " 46706723823",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anders",
   "lastName": "Olausson",
   "email": "anders.m.olausson@claremont.se",
   "phone": " 460703808090",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Carl-Johan",
   "lastName": "Nordh",
   "email": "carl-johan.nordh@claremont.se",
   "phone": " 46707818980",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Christer",
   "lastName": "Mörling",
   "email": "christer.morling@claremont.se",
   "phone": " 46708993549",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Emanuel",
   "lastName": "Ramsell",
   "email": "emanuel.ramsell@claremont.se",
   "phone": " 460706568531",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Herbert",
   "lastName": "Rosén",
   "email": "herbert.rosen@claremont.se",
   "phone": " 4646705211621",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jrgen",
   "lastName": "Damberg",
   "email": "jorgen.damberg@claremont.se",
   "phone": " 460730746689",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mattias",
   "lastName": "Snäll",
   "email": "mattias.snall@claremont.se",
   "phone": " 460739462431",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Olga",
   "lastName": "Tytarenko",
   "email": "olga.tytarenko@claremont.se",
   "phone": " 460762187244",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Patrik",
   "lastName": "Ohlsson",
   "email": "patrik.ohlsson@claremont.se",
   "phone": " 460761442345",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Per",
   "lastName": "Norstad",
   "email": "per.norstad@claremont.se",
   "phone": " 460702 784462",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Richard",
   "lastName": "Helsing",
   "email": "richard.helsing@claremont.se",
   "phone": " 46736546463",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Åsa",
   "lastName": "Liljeblad",
   "email": "asa.liljeblad@claremont.se",
   "phone": " 460709564510",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Örjan",
   "lastName": "Svensson",
   "email": "orjan.svensson@claremont.se",
   "phone": " 46730746717",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Wallén",
   "email": "anna.wallen@claremont.se",
   "phone": " 46700920535",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Oskar",
   "lastName": "Lind",
   "email": "oskar.lind@claremont.se",
   "phone": " 46707263111",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Bodil",
   "lastName": "Carlsson",
   "email": "bodil.carlsson@claremont.se",
   "phone": " 460767922626",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Bwar",
   "lastName": "Maroof",
   "email": "bwar.maroof@claremont.se",
   "phone": " 460704335075",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Diana",
   "lastName": "Hvozdz",
   "email": "diana.hvozdz@claremont.se",
   "phone": " 46768352884",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Helge",
   "lastName": "Björk",
   "email": "helge.bjork@claremont.se",
   "phone": " 460721774121",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jacob",
   "lastName": "Hedman",
   "email": "jacob.hedman@claremont.se",
   "phone": " 460761666009",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jana",
   "lastName": "Prihodko",
   "email": "jana.prihodko@claremont.se",
   "phone": " 460762183021",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jayson",
   "lastName": "Gregory",
   "email": "jayson.gregory@claremont.se",
   "phone": " 46734 481 350",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Hsieh",
   "email": "marcus.hsieh@claremont.se",
   "phone": " 46737838778",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Maria",
   "lastName": "Hansson",
   "email": "maria.hansson@claremont.se",
   "phone": " 460790798433",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Martin",
   "lastName": "Lövlie",
   "email": "martin.lovlie@claremont.se",
   "phone": " 460768776437",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "My",
   "lastName": "Strandberg",
   "email": "my.strandberg@claremont.se",
   "phone": " 460707536964",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Soleiman",
   "lastName": "Bourramman",
   "email": "soleiman.bourramman@claremont.se",
   "phone": " 460729044941",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Svante",
   "lastName": "Cedergårdh",
   "email": "svante.cedergardh@claremont.se",
   "phone": " 460708305438",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tommy",
   "lastName": "Månström",
   "email": "tommy.manstrom@claremont.se",
   "phone": " 460705612030",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andreas",
   "lastName": "Källbom",
   "email": "andreas.kallbom@claremont.se",
   "phone": " 4646703315433",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Hussein",
   "lastName": "Al-sahaf",
   "email": "hussein.alsahaf@claremont.se",
   "phone": " 46707866991",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Kvarnryd",
   "email": "johan.kvarnryd@claremont.se",
   "phone": " 46739388249",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Khon",
   "lastName": "Trinh",
   "email": "khon.trinh@claremont.se",
   "phone": " 460761305733",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Markus",
   "lastName": "Forsberg",
   "email": "markus.forsberg@claremont.se",
   "phone": " 46707386309",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mert",
   "lastName": "Curku",
   "email": "mert.curku@claremont.se",
   "phone": " 460739597291",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Peter",
   "lastName": "Hansen",
   "email": "peter.hansen@claremont.se",
   "phone": " 460709830539",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Reza",
   "lastName": "Hashemi",
   "email": "reza.hashemi@claremont.se",
   "phone": " 46704673998",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tommy",
   "lastName": "Nireus",
   "email": "tommy.nireus@claremont.se",
   "phone": " 460732751707",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Aki",
   "lastName": "Ravelin",
   "email": "aki.ravelin@claremont.se",
   "phone": " 460702011256",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Arodén",
   "email": "anna.aroden@claremont.se",
   "phone": " 46737664190",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Tribbler",
   "email": "anna.tribbler@claremont.se",
   "phone": " 460728797751",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Annika",
   "lastName": "Mossberg",
   "email": "annika.mossberg@claremont.se",
   "phone": " 46736360936",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Caroline",
   "lastName": "åkerblom",
   "email": "caroline.akerblom@claremont.se",
   "phone": " 460707609733",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Daniel",
   "lastName": "Persson",
   "email": "daniel.persson@claremont.se",
   "phone": " 460768611525",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Elena",
   "lastName": "Mircevska",
   "email": "elena.mircevska@claremont.se",
   "phone": " 460707782586",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Emil",
   "lastName": "Eriksson",
   "email": "emil.eriksson@claremont.se",
   "phone": " 460706604775",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Helen",
   "lastName": "Xin Xia",
   "email": "helen.xia@claremont.se",
   "phone": " 46734449172",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jimi",
   "lastName": "Wikman",
   "email": "jimi.wikman@claremont.se",
   "phone": " 46733370307",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jimmy",
   "lastName": "Leonardsson",
   "email": "jimmy.leonardsson@claremont.se",
   "phone": " 46703549970",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Bergman",
   "email": "johan.bergman@claremont.se",
   "phone": " 460703555323",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Klingsdal",
   "email": "jonas.klingsdal@claremont.se",
   "phone": " 460736631001",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonatan",
   "lastName": "Lidström",
   "email": "jonatan.lidstrom@claremont.se",
   "phone": " 46734449225",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Josefine",
   "lastName": "Schönebeck",
   "email": "josefine.schonebeck@claremont.se",
   "phone": " 460730305898",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Leo",
   "lastName": "Drougge",
   "email": "leo.drougge@claremont.se",
   "phone": " 460709569828",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Loa",
   "lastName": "Branner",
   "email": "loa.branner@claremont.se",
   "phone": " 46735062656",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Mattias",
   "lastName": "Berkesten",
   "email": "mattias.berkesten@claremont.se",
   "phone": " 460707206669",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "My",
   "lastName": "Amori",
   "email": "my.amori@claremont.se",
   "phone": " 460706086655",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Osborne",
   "lastName": "von Waldegg",
   "email": "osborne.von.waldegg@claremont.se",
   "phone": " 460733668833",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sofi",
   "lastName": "Ragnefors",
   "email": "sofi.ragnefors@claremont.se",
   "phone": " 4646 70-768 87 78",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tommy",
   "lastName": "Marshall",
   "email": "tommy.marshall@claremont.se",
   "phone": " 46702116891",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Veronica",
   "lastName": "Wallström",
   "email": "veronica.wallstrom@claremont.se",
   "phone": " 460706999180",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Yelena",
   "lastName": "Koselnik",
   "email": "yelena.koselnik@claremont.se",
   "phone": " 460763395221",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ylva",
   "lastName": "Boske",
   "email": "ylva.boske@claremont.se",
   "phone": " 4670 659 40 40",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Andreas",
   "lastName": "Karanikis",
   "email": "andreas.karanikis@claremont.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jonas",
   "lastName": "Nabseth",
   "email": "jonas.nabseth@gmail.com",
   "phone": " 46704821114",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Filip",
   "lastName": "Widén Widstrom",
   "email": "filip.widen-wikstrom@claremont.se",
   "phone": " 46702394825",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Malin",
   "lastName": "Heniemann",
   "email": "malin.heinemann@claremont.se",
   "phone": " 46702322300",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tom",
   "lastName": "Althin",
   "email": "tom.althin@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Towe",
   "lastName": "Rising",
   "email": "towe.rising@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "David",
   "lastName": "Knutsson",
   "email": "david.knutsson@hyperisland.se",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Peter",
   "lastName": "Najde",
   "email": "peter.najde@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Aidan",
   "lastName": "Jack",
   "email": "aidan.jack@protonmail.com",
   "phone": " 46729975878",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Martin",
   "lastName": "Sternelius",
   "email": "martin.sternelius@gmail.com",
   "phone": " 460736761213",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Rebecca",
   "lastName": "Cumberbatch",
   "email": "rebeccas.cumberbatch@gmail.com",
   "phone": " 46704099951",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Safin",
   "lastName": "Ayob",
   "email": "safin.ay10@gmail.com",
   "phone": " 46762761479",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Erik",
   "lastName": "Borg",
   "email": "erikborg51@gmail.com",
   "phone": " 460707455347",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Claudia",
   "lastName": "Wikström",
   "email": "claudia.wikstrom@hotmail.com",
   "phone": " 460707403334",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Patricia",
   "lastName": "Diberg",
   "email": "patricia.diberg@gmail.com",
   "phone": " 46727116376",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Jolina",
   "lastName": "Noresson",
   "email": "jolinanoresson@gmail.com",
   "phone": " 46765526704",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Felix",
   "lastName": "Richnau",
   "email": "felixrichnau@gmail.com",
   "phone": " 460730703331",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Ahmed",
   "lastName": "Ali",
   "email": "ahmed--a@live.se",
   "phone": " 460704554826",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Markus",
   "lastName": "Elfving",
   "email": "markuselfving@hotmail.com",
   "phone": " 46703957502",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Aina",
   "lastName": "Griksaite",
   "email": "ainag@kth.se",
   "phone": " 460707128887",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Lovisa",
   "lastName": "Holmgren",
   "email": "lovisa.holmgren1@gmail.com",
   "phone": " 460702636419",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Fenni",
   "lastName": "Johansson",
   "email": "fennijohansson@gmail.com",
   "phone": " 46760901494",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Anna",
   "lastName": "Eriksson",
   "email": "anna.el.eriksson94@gmail.com",
   "phone": " 46700436482",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johan",
   "lastName": "Lundqvist",
   "email": "johan3040@hotmail.com",
   "phone": " 46707739868",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Linnea",
   "lastName": "Skärdin",
   "email": "linneaskardin@gmail.com",
   "phone": " 46739787317",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Nathalie",
   "lastName": "Hedin",
   "email": "nathalie.hedin@hotmail.com",
   "phone": " 460702335993",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Oscar",
   "lastName": "Törnquist",
   "email": "tornquist93@gmail.com",
   "phone": " 46700628441",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Isabelle",
   "lastName": "Almquist",
   "email": "almquist.isabelle@gmail.com",
   "phone": " 460703342464",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Madeleine",
   "lastName": "Angergård",
   "email": "madeleine.angergard@gmail.com",
   "phone": " 46738263193",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Carlesål",
   "email": "marcus.carlestal@hotmail.com",
   "phone": " 46700910032",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Johanna",
   "lastName": "Bromark",
   "email": "johanna.bromark@gmail.com",
   "phone": " 46706662052",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Marcus",
   "lastName": "Hogler",
   "email": "mhogler@kth.se",
   "phone": " 46707195125",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Axel",
   "lastName": "Nyström",
   "email": "nystromaxel95@gmail.com",
   "phone": " 46736328266",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Edith",
   "lastName": "Hörnlund",
   "email": "edith.hornlund@gmail.com",
   "phone": " 46734307019",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Petra",
   "lastName": "Vikner",
   "email": "petra.wikner@hotmail.com",
   "phone": " 46702873063",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Sanni",
   "lastName": "Nyström",
   "email": "sanninystrom@hotmail.com",
   "phone": " 460738444989",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Gustaf",
   "lastName": "Gustafsson",
   "email": "gustafagustafsson@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Louise",
   "lastName": "Hillin",
   "email": "louise.hillin@live.se",
   "phone": " 46762740157",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Lilly",
   "lastName": "Ruijun Wang",
   "email": "lilly.ruijun.wang@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Felix",
   "lastName": "Risén",
   "email": "felixrisen@gmail.com",
   "phone": " 460730298356",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Henrik",
   "lastName": "Ulvenäs",
   "email": "henrik.ulvenas@gmail.com",
   "phone": "",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Malin",
   "lastName": "Aldrin",
   "email": "malin@aldrin.se",
   "phone": " 46708-361219",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Matteo",
   "lastName": "Filannino",
   "email": "matteo.filannino@claremont.se",
   "phone": " 46736200543",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 },
 {
   "firstName": "Tonje",
   "lastName": "Berg",
   "email": "tonjeberg_@hotmail.com",
   "phone": " 47095470764",
   "activity": "Hike",
   "theme1": "Code",
   "theme2": "Leadership",
   "meeting1": "Grupp 1",
   "meeting2": "I Lobbyn"
 }
]